version: "3.7"

services:
  web:
    build: ./
    # command: >
    #   sh -c "python manage.py migrate"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    image: web-image
    env_file: 
      - ./.env.dev
    depends_on: 
      - db
      # - rabbitmq

  db:
    image: postgres:10.17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=iyb_user
      - POSTGRES_PASSWORD=iyb_pass
      - POSTGRES_DB=insure_your_buddy
    ports:
      - "5432:5432"

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   hostname: some-rabbit
  #   ports: 
  #     - "5762:5762"
  #     - "15672:15672"
  #   restart: on-failure

  # celery_worker:
  #   command: celery -A insurance worker -l  info -P solo
  #   depends_on: 
  #     - web
  #     - db
  #     - rabbitmq
  #   image: web-image

  # elasticsearch:
  #   image: elasticsearch:7.13.4
  #   environment:
  #     - discovery.type=single-node
  #   hostname: elasticsearch
  #   ports:
  #     - "9200:9200"
  
volumes:
  postgres_data: