version: "3.8"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: some-rabbit
    ports: 
      - 5762:5762
      - 15672:15672