# Generated by Django 3.2 on 2021-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Vehicle'), (2, 'Home insurance'), (3, 'Life'), (4, 'Property'), (5, 'Combo')])),
                ('minimal_payment', models.PositiveIntegerField()),
                ('term', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('customers_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
