# Generated by Django 3.2 on 2021-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insure_your_buddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceservice',
            name='customers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insuranceservice',
            name='description',
            field=models.TextField(),
        ),
    ]
