# Generated by Django 3.2 on 2021-08-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insure_your_buddy', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceservice',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vehicle'), (2, 'Home'), (3, 'Life'), (4, 'Property'), (5, 'Combo')]),
        ),
    ]
